Fixing several small documentation bugs
phenopackets/phenopacket-schema pull request #385
Opened 2024-04-05 02:00 UTC by ielis

The PR fixes several small inaccuracies in the documentation, mostly deviations from the protobuf schema.

Fixes #339, #344, #350, #351

2024-06-28 12:30 UTC, pnrobinson requested changes
Looks fine but there is not reason for the change in interpretation/Miller syndrome

2024-07-04 07:42 UTC, ielis commented
Hi @pnrobinson 
I will fix this soon, but there is one more thing I'd like to check. Should we italicize gene symbols? Currently, the documentation does not italicize human gene symbols.

2024-07-04 09:31 UTC, pnrobinson commented
gene symbols should alsways be italicized!

2024-07-04 12:07 UTC, pnrobinson commented on docs/interpretation.rst
> +      - interpretationStatus: "CANDIDATE"
In this case the interpretationStatus should be CAUSAL, this was a published case!

2024-07-04 12:08 UTC, pnrobinson requested changes
One small change requested then we can merge!

2024-07-04 17:11 UTC, pnrobinson commented on docs/interpretation.rst
> +      - interpretationStatus: "CANDIDATE"
Maybe it does not fit well with the description, but it si not wrong, I will merge

2024-07-04 17:11 UTC, merged